services:
  db:
    image: mysql:8.0.32
    platform: linux/amd64 #mac環境で必須なことがあるらしい
    env_file: ./db/sample.env
    container_name: jobreco_db
    build:
      context: ./db
      dockerfile: ../docker/db.Dockerfile
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      # - ./db:/var/lib/mysql #ここにデータ永続化するためのファイルが入る。
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci 

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=jobreco_db
    depends_on:
      db:
        condition: service_healthy

volumes:
  node_modules: